### ISSUE TITLE
link-handling-mod-hugo-dfd taken down

### ISSUE THREAD

**Issue by farlee2121** [danielfdickinson/image-handling-mod-hugo-dfd#100]
Hello, my hugo repo was depending on link-handling-mod-hugo-dfd. 

I you don't wish to maintain the project, could I get a copy to keep my code base running?

**Comment by danielfdickinson** [comment]
Certainly, I will do that tonight. Sorry for the inconvenience.

Daniel F. Dickinson<https://www.danielfdickinson.ca/> (he/him/they/them)
B. Computing
Wild Tech 'Garden'<https://www.wildtechgarden.ca/>

________________________________
From: Spencer Farley ***@***.***>
Sent: November 24, 2023 4:30 PM
To: danielfdickinson/image-handling-mod-hugo-dfd ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [danielfdickinson/image-handling-mod-hugo-dfd] link-handling-mod-hugo-dfd taken down (Issue #100)


Hello, my hugo repo was depending on link-handling-mod-hugo-dfd.

I you don't wish to maintain the project, could I get a copy to keep my code base running?

**Comment by danielfdickinson** [comment]
Made a private copy from which you can make a copy for your use (you can make the copy public if you wish, I just don't wish to advertise it as being available from here).

**Comment by farlee2121** [comment]
I got a fork made. Thank you very much!
