### ISSUE TITLE
Add info about 'hugo mod init' to install section

### ISSUE THREAD

**Issue by callumgare** [danielfdickinson/image-handling-mod-hugo-dfd#32]
Thanks for such a handy module! It seems like just what I'm looking for. Unfortunately I'm running into trouble when following the install instructions. I'm very new to Hugo so I'm sure I'm doing something dumb though.

![Screen Shot 2022-07-02 at 17 52 10](https://user-images.githubusercontent.com/346340/176992006-0da16fc8-ce23-4eae-9236-1c6f5c101c4f.png)

**Comment by callumgare** [comment]
Figured out what I was doing wrong. I hadn't initialised the site as a go module. For anyone else experiencing this run `hugo mod init` and that will explain how to init.

Would it be possible to mention that in the "Basic usage" section of the README for noobs like me? Cheers :)

**Comment by danielfdickinson** [comment]
Hi. Will do, and am glad you figured it out.
