### ISSUE TITLE
Drop dependency on link-handling module

### ISSUE THREAD

**Issue by danielfdickinson** [danielfdickinson/image-handling-mod-hugo-dfd#34]
And update shortcode, partials, and README appropriately.

**Comment by h-enk** [comment]
Is this related to https://github.com/h-enk/doks/issues/820?

**Comment by danielfdickinson** [comment]
@h-enk Yes. I want to avoid that kind of problem when someone uses image-handling without also using link-handling from me. I'll work on this either today (Monday July 11) or tomorrow (Tuesday July 12).
